name: chat_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_screenutil: ^5.9.3
  dio_smart_retry: ^7.0.1
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  shimmer: ^3.0.0
  equatable: ^2.0.7
  injectable: ^2.5.0
  pinput: ^5.0.1
  get_it: ^8.0.3
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  japx: ^2.2.0
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  cached_network_image: ^3.4.1
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Black.ttf
        - asset: assets/font/Poppins-BlackItalic.ttf
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-Light.ttf
        - asset: assets/font/Poppins-Medium.ttf
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-SemiBoldItalic.ttf
        - asset: assets/font/Poppins-Thin.ttf

